"""create_accounts_table_with_constraints

Revision ID: 42eb1e86177d
Revises: 02d61bc06799
Create Date: 2026-06-26 09:10:43.189526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '42eb1e86177d'
down_revision: Union[str, Sequence[str], None] = '02d61bc06799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('version', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('accounts_account_number_key'), 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index('ix_accounts_account_type_status', 'accounts', ['account_type', 'status'], unique=False)
    op.create_index('ix_accounts_customer_status', 'accounts', ['customer_id', 'status'], unique=False)
    op.create_index('ix_accounts_status_balance', 'accounts', ['status', 'balance'], unique=False)
    op.drop_constraint(op.f('accounts_updated_by_fkey'), 'accounts', type_='foreignkey')
    op.drop_constraint(op.f('accounts_created_by_fkey'), 'accounts', type_='foreignkey')
    op.drop_constraint(op.f('accounts_customer_id_fkey'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'accounts', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'accounts', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_customer_id_fkey'), 'accounts', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('accounts_created_by_fkey'), 'accounts', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('accounts_updated_by_fkey'), 'accounts', 'users', ['updated_by'], ['id'])
    op.drop_index('ix_accounts_status_balance', table_name='accounts')
    op.drop_index('ix_accounts_customer_status', table_name='accounts')
    op.drop_index('ix_accounts_account_type_status', table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=False)
    op.create_unique_constraint(op.f('accounts_account_number_key'), 'accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('accounts', 'version')
    # ### end Alembic commands ###